---
keys:
  release: BaculaSystems-Public-Signature-08-2017.asc
  beta: BaculaSystems-Public-Signature-08-2017.asc
  nightly: nightly-misc/BaculaSystems-Nightly-Signature.asc

sdplugins:
  acsls:
    directory: acsls 
    name: acsls
    package_name: bacula-enterprise-acsls
  
  aligned:
    directory: aligned
    name: aligned
    package_name: bacula-enterprise-aligned

  catalyst:
    directory: catalyst
    name: catalyst
    package_name: bacula-enterprise-storage-catalyst-plugin

  cloud-amazon:
    directory: cloud-s3
    name: cloud-s3
    package_name: bacula-enterprise-cloud-storage-s3

  cloud-amazon-glacier:
    directory: cloud-s3
    name: cloud-s3
    package_name: bacula-enterprise-cloud-storage-s3

  cloud-azure:
    directory: cloud-azure
    name: cloud-azure
    package_name: bacula-enterprise-cloud-storage-azure

  cloud-google:
    directory: cloud-google
    name: cloud-google
    package_name: bacula-enterprise-cloud-storage-google

  cloud-oracle:
    directory: cloud-oracle
    name: cloud-oracle
    package_name: bacula-enterprise-cloud-storage-oracle

  cloud-s3:
    directory: cloud-s3
    name: cloud-s3
    package_name: bacula-enterprise-cloud-storage-s3

  cloud-glacier:
    directory: cloud-glacier
    name: cloud-glacier
    package_name: bacula-enterprise-cloud-storage-glacier

  dedup:
    directory: dedup 
    name: dedup
    package_name: bacula-enterprise-dedup-plugin

  dedup2:
    directory: dedup 
    name: dedup
    package_name: bacula-enterprise-dedup-plugin

  dedup-legacy:
    directory: dedup 
    name: dedup
    package_name: bacula-enterprise-dedup-plugin

  shstore:
    directory: shstore
    name: shstore
    package_name: bacula-enterprise-shstore

  sir:
    directory: single-item-restore
    name: single-item-restore
    package_name: bacula-enterprise-single-item-restore
