---
- name: Install pre-requisite packages
  ansible.builtin.apt:
    name:
      - wget
    state: present
  register: result

- name: Download the Microsoft repository
  ansible.builtin.get_url:
    url: "https://packages.microsoft.com/config/{{ ansible_distribution|lower }}/{{ ansible_distribution_major_version }}/packages-microsoft-prod.deb"
    dest: /tmp/packages-microsoft-prod.deb

- name: create the /etc/apt/keyrings directory if it does not exist
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Import Microsoft GPG key
  ansible.builtin.shell: |
    curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | tee /etc/apt/keyrings/microsoft.gpg > /dev/null
  args:
    creates: /etc/apt/keyrings/microsoft.gpg

- name: Register the Microsoft repository keys
  ansible.builtin.apt:
    deb: /tmp/packages-microsoft-prod.deb

- name: Update the list of packages after we added packages.microsoft.com
  ansible.builtin.apt:
    update_cache: true

- name: Install PowerShell
  ansible.builtin.apt:
    name: powershell

- name: check powershell version installed
  ansible.builtin.shell: pwsh --version
  register: powershell_version

- debug: msg="{{ powershell_version.stdout.split('\n') }}"
- debug: msg="{{ powershell_version.stderr.split('\n') }}"
