---
- name: Install pre-requisite packages
  ansible.builtin.apt:
    name:
      - wget
    state: present
  register: result

- name: Download the Microsoft repository
  ansible.builtin.get_url:
    url: "https://packages.microsoft.com/config/{{ ansible_distribution|lower }}/{{ ansible_distribution_major_version }}/packages-microsoft-prod.deb"
    dest: /tmp/packages-microsoft-prod.deb

- name: Install Microsoft GPG key
  ansible.builtin.apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Register the Microsoft repository keys
  ansible.builtin.apt:
    deb: /tmp/packages-microsoft-prod.deb

- name: Update the list of packages after we added packages.microsoft.com
  ansible.builtin.apt:
    update_cache: true

- name: Install PowerShell
  ansible.builtin.apt:
    name: powershell

- name: check powershell version installed
  ansible.builtin.shell: pwsh --version
  register: powershell_version

- debug: msg="{{ powershell_version.stdout.split('\n') }}"
- debug: msg="{{ powershell_version.stderr.split('\n') }}"
