---
- name: import Microsoft key
  shell: sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
- name: add azure-cli repo
  shell: "sudo dnf install -y https://packages.microsoft.com/config/rhel/10/packages-microsoft-prod.rpm"
