- name: Add Google Cloud SDK signing key to specific keyring file
  ansible.builtin.apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    keyring: /etc/apt/keyrings/cloud-google.gpg
    state: present

- name: Enable Google Cloud SDK repository
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/cloud-google.gpg] https://packages.cloud.google.com/apt cloud-sdk main
    filename: google-cloud-sdk
    state: present
