---
keys:
  release: BaculaSystems-Public-Signature-08-2017.asc
  beta: BaculaSystems-Public-Signature-08-2017.asc
  nightly: BaculaSystems-Nightly-Signature.asc

dirplugins:
  bguardian:
    name: bguardian
    directory: bguardian
    package_name: bacula-enterprise-bguardian-dir-plugin

  totp:
    name: totp
    directory: bin
    package_name: bacula-enterprise-totp-dir-plugin

  wazuh:
    name: wazuh
    directory: bin
    package_name: bacula-enterprise-wazuh-rules
