---
- name: install postgresql-server
  yum:
    name: postgresql-server
    state: latest
  register: result
  retries: 3
  delay: 10
  failed_when:
    - (result.rc != 0) or (result.stderr is defined and result.stderr | length > 0)
