---
# This task list will install the latest Bacula Enterprise version
# available in the repository files added
# This will allow the upgrade of existent BEE install by
# adding the new repo file and using this same role to update
- name: install Bacula Enteprise Edition postgresql
  yum:
    name: bacula-enterprise-postgresql
    state: latest
  register: result
  retries: 3
  delay: 10
  failed_when: >
    ( result.rc != 0 ) or
    ( result.stderr is defined and result.stderr | length > 0 )

- debug: msg="{{ result.stderr.split('\n') }}"
  when: >
    ( result.rc != 0 ) or
    ( result.stderr is defined )
